language: node_js
sudo: false
npm_args: --ws:native
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
before_install:
  - "if [[ $(node --version) == v0.8.* ]]; then npm install -g npm@2.1.18; fi"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
    - node_js: "0.9"
    - node_js: "iojs-v3"
