environment:
  matrix:
    - nodejs_version: '11'
    - nodejs_version: '10'
    - nodejs_version: '8'
    - nodejs_version: '6'
matrix:
  fast_finish: true
platform:
  - x86
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: off
